# fly.toml app configuration file generated for stagio-frontend on 2025-07-31T20:25:15-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'stagio-frontend'
primary_region = 'iad'

[build]

[env]
  NEXT_PUBLIC_API_BASE_URL = 'https://api.stagio.live'
  NEXT_PUBLIC_API_REFRESH_URL = 'https://api.stagio.live/auth/refresh'
  NEXT_PUBLIC_RTMP_URL = 'rtmp://rtmp.stagio.live:1935/live'
  NEXT_PUBLIC_SSE_URL = 'https://api.stagio.live/streams/view/subscribe'
  NEXT_PUBLIC_WEBSOCKET_URL = 'https://api.stagio.live/ws'
  NEXT_TELEMETRY_DISABLED = '1'
  NODE_ENV = 'production'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
